# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.2
language: swift
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --verbose #--project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace ShoppingApp.xcworkspace -scheme ShoppingApp -sdk iphonesimulator14.2 ONLY_ACTIVE_ARCH=NO | xcpretty
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/CS_Common_Utils.xcworkspace -scheme CS_Common_Utils-Example -sdk iphonesimulator14.2 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint --allow-warnings
